<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6nMyUZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6nMyUZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6nMyUZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV6nMyUZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV6nMyUZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V6nMyUZ',
    'container.build_id' => '34f0c259',
    'container.build_time' => 1607006465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6nMyUZ');
